export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const ITEM_LIST_FAIL = "ITEM_LIST_FAIL";

export const ITEM_DETAILS_REQUEST = "ITEM_DETAILS_REQUEST";
export const ITEM_DETAILS_SUCCESS = "ITEM_DETAILS_SUCCESS";
export const ITEM_DETAILS_FAIL = "ITEM_DETAILS_FAIL";

export const ITEM_ADD_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_ADD_SUCCESS = "ITEM_ADD_SUCCESS";
export const ITEM_ADD_FAIL = "ITEM_ADD_FAIL";
